name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  slideable: ^0.0.2 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  uuid: ^4.5.1
  intl: ^0.20.1
  build_runner: ^2.4.14
  provider: ^6.1.2
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
