name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  slideable: ^0.0.2 
  uuid: ^4.5.1
  intl: ^0.20.1
  provider: ^6.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
